addpath( 'functions' );
addpath( 'BANPE' );
addpath(['functions' filesep 'vgg_multiview']);
addpath(['functions' filesep 'VPtoolbox' filesep 'Cexp']);
addpath(['functions' filesep 'VPtoolbox' filesep 'robotics3D']);
addpath(['functions' filesep 'VPtoolbox' filesep 'VanishingPoint' filesep 'Calibrated']);
addpath(['functions' filesep 'VPtoolbox' filesep 'VanishingPoint' filesep 'Utils']);
addpath(['functions' filesep 'RPnL']);
addpath(['functions' filesep 'PnL_analysis']);
addpath(['functions' filesep 'PnL_analysis' filesep 'epnp']);
addpath( 'BANPnL' );
return;
